#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

./build-linux-x86_64

./build-linux-x86

./build-windows-x86_64

./build-windows-x86

./build-osx-x86_64

./build-android
