#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

TARGET=Release-Linux-x86_64

../refresh-build-date > log-${TARGET}

codeblocks --build --target="${TARGET}" ../../project.cbp >> log-${TARGET}
