#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	../Build-Date-Linux-x86_64 $PROJECT_DIRECTORY > "$PROJECT_DIRECTORY/log-Release-Android"

	../Android-Prep-Linux-x86_64 $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	cd $PROJECT_DIRECTORY/development/android/build-scripts/linux/

	./build >> "$PROJECT_DIRECTORY/log-Release-Android"

	./ant-release-build >> "$PROJECT_DIRECTORY/log-Release-Android"
else
	echo "build-android - build the android target for the passed project"
	echo "Usage: build-android PROJECT_DIRECTORY"
fi
