#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	../Build-Date-Linux-x86_64 $PROJECT_DIRECTORY > "$PROJECT_DIRECTORY/log-Release-Android"

	cd ../
	./Android-Prep-Linux-x86_64 $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"
	cd $DIR

	android/linux/build $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	android/linux/ant $PROJECT_DIRECTORY release >> "$PROJECT_DIRECTORY/log-Release-Android"
else
	echo "build-android - build the android target for the passed project"
	echo "Usage: build-android PROJECT_DIRECTORY"
fi
