#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	chmod +x $PROJECT_DIRECTORY/development/android/build-scripts/linux/*

	chmod -x $PROJECT_DIRECTORY/development/android/build-scripts/linux/ant.properties
	chmod -x $PROJECT_DIRECTORY/development/android/build-scripts/linux/local.properties
else
	echo "make-executable - make android build scripts for the passed project executable"
	echo "Usage: make-executable PROJECT_DIRECTORY"
fi
