#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
    echo "Initiating Cheesy Build System in detached mode"

    NAME=build

    screen -m -d -S $NAME ./build "$@"
else
    echo "buildDetached - build a Cheese Engine project in a detached screen session"
	echo "Usage: buildDetached PROJECT-DIRECTORY"
	echo "PROJECT-DIRECTORY may be located anywhere except under '~/build-server/projects/'"
	echo "Do 'buildDetached clean' to empty the projects directory"
fi
