#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
    export DISPLAY=:0.0

    echo "Initiating Cheesy Build System in detached mode"

    NAME=build

    screen -m -d -S $NAME ./build "$@"
else
    echo "remote-build-detached - build a Cheese Engine project remotely in a detached screen session"
	echo "Usage: remote-build-detached PROJECT-DIRECTORY"
	echo "PROJECT-DIRECTORY may be located anywhere except under '~/build-server/projects/'"
	echo "Do 'remote-build-detached clean' to empty the projects directory"
fi
