#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	IMAGES_DIRECTORY="$PROJECT_DIRECTORY/data/images"

	# Remove all files and directories except for .gitkeep
	rm -rf $IMAGES_DIRECTORY/*

	# Remove the icon
	rm -f "$PROJECT_DIRECTORY/standard.ico"
else
	echo "clean-images - clean up all image data files for the passed project"
	echo "Usage: clean-images PROJECT-DIRECTORY"
fi
