#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

rm -rf "CMakeFiles/"
rm -rf ".objs/"

rm -rf "bin/"
rm -rf "include/"
rm -rf "lib/"
rm -rf "share/"
rm -f "lib64"
rm -f "pyvenv.cfg"

rm -f *Windows-x86_64.a
rm -f *Windows-Debug-x86_64.a
rm -f *Linux-x86_64.a
rm -f *Linux-Debug-x86_64.a
rm -f *macOS-x86_64.a

rm -f "docs/build-information"

rm -f "CMakeCache.txt"
rm -f "Makefile"
rm -f "cmake_install.cmake"
rm -f "compile_commands.json"

rm -f "log-Release-Android"
rm -f "log-Release-Linux-x86_64"
rm -f "log-Debug-Linux-x86_64"
rm -f "log-Release-macOS-x86_64"
rm -f "log-Release-Windows-x86_64"

rm -f *.dll
rm -f *.depend
rm -f *.cscope_file_list

rm -f "Thumbs.db"
rm -f ".DS_Store"
