#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	export NDK_PROJECT_PATH="$PROJECT_DIRECTORY/development/android"

	/home/tails/build-server/android/android-ndk/ndk-build clean
else
	echo "clean - run ndk-build clean on the passed project"
	echo "Usage: clean PROJECT_DIRECTORY"
fi
