#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./build-target $PROJECT_DIRECTORY Release-Linux-x86_64

	./build-target $PROJECT_DIRECTORY Debug-Linux-x86_64

	./build-target $PROJECT_DIRECTORY Release-Windows-x86_64

	./build-target $PROJECT_DIRECTORY Release-macOS-arm64

	./build-engine-android $PROJECT_DIRECTORY

	../../build-information $PROJECT_DIRECTORY
else
	echo "build-engine - build all targets for the Cheese Engine library located at the passed project directory"
	echo "Usage: build-engine PROJECT-DIRECTORY"
fi
