#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

KEY_STORE_LOCATION="\/home\/tails\/build-server\/android\/keystore\/cheese-and-bacon-games-app-bundle\.keystore"
KEY_PASSWORDS_LOCATION="/home/tails/build-server/android/keystore/key-app-bundle"
KEY_ALIAS="key0"

check_status () {
	local status=$?
	if [ $status -ne 0 ]; then
		exit $status
	fi
}

if [ -n "$PROJECT_DIRECTORY" ]; then
	../../build-date $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	./clean-android $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	cd ../../
	./android-prep $PROJECT_DIRECTORY $KEY_STORE_LOCATION $KEY_PASSWORDS_LOCATION $KEY_ALIAS >> "$PROJECT_DIRECTORY/log-Release-Android"
	cd $DIR

	android/build "$PROJECT_DIRECTORY" "release" >> "$PROJECT_DIRECTORY/log-Release-Android"

	check_status
else
	echo "build-android - build the android target for the passed project"
	echo "Usage: build-android PROJECT-DIRECTORY"
fi
