#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1
ANDROID_ABI_TARGETS=$2

check_status () {
	local status=$?
	if [ $status -ne 0 ]; then
		exit $status
	fi
}

read_android_key () {
	IFS='=' read -ra LINE_PARTS <<< "$1"

	if [ ${#LINE_PARTS[@]} -ge 2 ]; then
		echo "${LINE_PARTS[1]}"
	else
		echo ""
	fi
}

if [ -n "$PROJECT_DIRECTORY" ]; then
	../../build-date $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	./clean-android $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	echo "Loading Android key" >> "$PROJECT_DIRECTORY/log-Release-Android"

	KEY_STORE_LOCATION=""
	KEY_PASSWORDS_LOCATION=""
	KEY_ALIAS=""

	if [ -f "${PROJECT_DIRECTORY}/development/build-system-android-key" ]; then
		while read line
		do
			if ! [[ $line =~ ^\# ]]; then
				if [[ $line =~ ^key_store_location ]]; then
					result=$(read_android_key "$line")

					if [ -n "$result" ]; then
						KEY_STORE_LOCATION="$result"
					fi
				fi

				if [[ $line =~ ^key_passwords_location ]]; then
					result=$(read_android_key "$line")

					if [ -n "$result" ]; then
						KEY_PASSWORDS_LOCATION="$result"
					fi
				fi

				if [[ $line =~ ^key_alias ]]; then
					result=$(read_android_key "$line")

					if [ -n "$result" ]; then
						KEY_ALIAS="$result"
					fi
				fi
			fi
		done <"${PROJECT_DIRECTORY}/development/build-system-android-key"
	fi

	cd ../../
	./android-prep "$PROJECT_DIRECTORY" "$KEY_STORE_LOCATION" "$KEY_PASSWORDS_LOCATION" "$KEY_ALIAS" "$ANDROID_ABI_TARGETS" >> "$PROJECT_DIRECTORY/log-Release-Android"
	cd $DIR

	android/build "$PROJECT_DIRECTORY" "release" >> "$PROJECT_DIRECTORY/log-Release-Android"

	check_status
else
	echo "build-android - build the android target for the passed project"
	echo "Usage: build-android PROJECT-DIRECTORY ANDROID-ABI-TARGETS"
fi
