#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./build-target "$PROJECT_DIRECTORY" "Release-Linux-x86_64"

	./build-target "$PROJECT_DIRECTORY" "Debug-Linux-x86_64"

	./build-target "$PROJECT_DIRECTORY" "Release-Windows-x86_64"

	./build-target "$PROJECT_DIRECTORY" "Release-macOS-arm64"

	ANDROID_ABI_TARGETS=""
	if [ -f "$PROJECT_DIRECTORY/development/build-system-targets" ]; then
		while read line
		do
			if [[ $line == Android* ]]; then
				ANDROID_ABI_TARGETS=$(echo $line | sed s/Android//)
			fi
		done <"$PROJECT_DIRECTORY/development/build-system-targets"
	fi
	./build-android "$PROJECT_DIRECTORY" "$ANDROID_ABI_TARGETS"
else
	echo "build-all - build all targets for the passed project"
	echo "Usage: build-all PROJECT-DIRECTORY"
fi
