#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./build-target $PROJECT_DIRECTORY Release-Linux-x86_64

	./build-target $PROJECT_DIRECTORY Release-Windows-x86_64

	./build-target $PROJECT_DIRECTORY Release-macOS-x86_64

	./build-android $PROJECT_DIRECTORY
else
	echo "build-all - build all targets for the passed project"
	echo "Usage: build-all PROJECT-DIRECTORY"
fi
