#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	chmod +x $PROJECT_DIRECTORY/development/android/clean-android
	chmod +x $PROJECT_DIRECTORY/development/android/android-prep

	$PROJECT_DIRECTORY/development/android/clean-android
	$PROJECT_DIRECTORY/development/android/android-prep

	android/linux/build $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	ANDROID_ABI_TARGETS="armeabi armeabi-v7a x86"

	ANDROID_ABI_RESULTS=""

	for d in $PROJECT_DIRECTORY/development/android/obj/local/* ; do
		PREFIX=$PROJECT_DIRECTORY/development/android/obj/local/
		SUFFIX=/
		LIB_NAME=${d#$PREFIX}
		LIB_NAME=${LIB_NAME%$SUFFIX}
		ANDROID_ABI_RESULTS="$ANDROID_ABI_RESULTS $LIB_NAME"

		if ! [ -e "$d/libRakNet.a" ]; then
			echo "build-engine-android failed for $PROJECT_DIRECTORY: missing library '$d/libRakNet.a'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2.a" ]; then
			echo "build-engine-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2.a'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2_image.a" ]; then
			echo "build-engine-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2_image.a'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2_mixer.a" ]; then
			echo "build-engine-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2_mixer.a'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libCheese-Engine.a" ]; then
			echo "build-engine-android failed for $PROJECT_DIRECTORY: missing library '$d/libCheese-Engine.a'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi
	done

	IFS=' ' read -a ARRAY <<< "$ANDROID_ABI_TARGETS"
	for i in "${ARRAY[@]}" ; do
		if ! [[ $ANDROID_ABI_RESULTS == *"$i"* ]]; then
			echo "build-engine-android failed for $PROJECT_DIRECTORY: missing ABI '$i'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi
	done
else
	echo "build-engine-android - build the android target for the Cheese Engine library located at the passed project directory"
	echo "Usage: build-engine-android PROJECT-DIRECTORY"
fi
