#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	rm -rf "$PROJECT_DIRECTORY/CMakeFiles/"
	rm -f "$PROJECT_DIRECTORY/CMakeCache.txt"
	rm -f "$PROJECT_DIRECTORY/Makefile"
	rm -f "$PROJECT_DIRECTORY/cmake_install.cmake"
	rm -f "$PROJECT_DIRECTORY/compile_commands.json"
else
	echo "clean-project - clean the passed project"
	echo "Usage: clean-project PROJECT-DIRECTORY"
fi
