#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./clean-target $PROJECT_DIRECTORY Release-Linux-x86_64

	./clean-target $PROJECT_DIRECTORY Release-Linux-x86

	./clean-target $PROJECT_DIRECTORY Cross-Compile-Windows-x86_64

	./clean-target $PROJECT_DIRECTORY Release-Windows-x86

	./clean-target $PROJECT_DIRECTORY Release-macOS-x86_64

	./clean-android $PROJECT_DIRECTORY
else
	echo "clean-all - clean all targets for the passed project"
	echo "Usage: clean-all PROJECT-DIRECTORY"
fi
