#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	rm -rf "$PROJECT_DIRECTORY/development/android/assets/"
	rm -rf "$PROJECT_DIRECTORY/development/android/bin/"
	rm -rf "$PROJECT_DIRECTORY/development/android/gen/"
	rm -rf "$PROJECT_DIRECTORY/development/android/libs/"
	rm -rf "$PROJECT_DIRECTORY/development/android/obj/"

	rm -rf "$PROJECT_DIRECTORY/development/android/jni/armeabi/"
	rm -rf "$PROJECT_DIRECTORY/development/android/jni/armeabi-v7a/"
	rm -rf "$PROJECT_DIRECTORY/development/android/jni/x86/"

	rm -f "$PROJECT_DIRECTORY/development/android/jni/include/SDL2"
	rm -f "$PROJECT_DIRECTORY/development/android/jni/include/SDL2_image"
	rm -f "$PROJECT_DIRECTORY/development/android/jni/include/SDL2_mixer"
	rm -f "$PROJECT_DIRECTORY/development/android/jni/include/RakNet"
	rm -f "$PROJECT_DIRECTORY/development/android/jni/include/boost"
	rm -f "$PROJECT_DIRECTORY/development/android/jni/include/cheese-engine"

	rm -rf "$PROJECT_DIRECTORY/development/android/jni/include/"

	rm -f "$PROJECT_DIRECTORY/development/android/ant.properties"
	rm -f "$PROJECT_DIRECTORY/development/android/local.properties"
else
	echo "clean-android - clean the android target for the passed project"
	echo "Usage: clean-android PROJECT-DIRECTORY"
fi
