#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1
TARGET=$2

if [ -n "$PROJECT_DIRECTORY" ] && [ -n "$TARGET" ]; then
	make -C "$PROJECT_DIRECTORY" "clean"

	rm -rf "$PROJECT_DIRECTORY/CMakeFiles/"
	rm -f "$PROJECT_DIRECTORY/CMakeCache.txt"
	rm -f "$PROJECT_DIRECTORY/Makefile"
	rm -f "$PROJECT_DIRECTORY/cmake_install.cmake"
else
	echo "clean-target - clean the passed target for the passed project"
	echo "Usage: clean-target PROJECT-DIRECTORY TARGET"
fi
