#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./clean-project $PROJECT_DIRECTORY

	./clean-android $PROJECT_DIRECTORY
else
	echo "clean-all - clean all targets for the passed project"
	echo "Usage: clean-all PROJECT-DIRECTORY"
fi
