#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

BUILD_HOME="/home/tails"

# QQQ
echo "DEPLOY SCRIPT STARTED"
echo "PROJECT_DIRECTORY: $PROJECT_DIRECTORY"
echo "BUILD_HOME: $BUILD_HOME"
echo "DIR: $DIR"
echo "ls $BUILD_HOME/build-server: $(ls $BUILD_HOME/build-server)"

if [ -n "$PROJECT_DIRECTORY" ]; then
	rm -rf "$BUILD_HOME/build-server/cheese-engine-previous"
	mv "$BUILD_HOME/build-server/cheese-engine/" "$BUILD_HOME/build-server/cheese-engine-previous"

	cp -r "$PROJECT_DIRECTORY" "$BUILD_HOME/build-server/cheese-engine"

	$BUILD_HOME/build-server/make_executable
else
	echo "deploy-engine -  deploy the specified Cheese Engine library"
	echo "Usage: deploy-engine CHEESE-ENGINE-DIRECTORY"
fi
