#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

KEY_PASSWORDS_LOCATION="/home/tails/build-server/android/keystore/key"

if [ -n "$PROJECT_DIRECTORY" ]; then
	../../build-date $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	cd ../../
	./android-prep $PROJECT_DIRECTORY $KEY_PASSWORDS_LOCATION >> "$PROJECT_DIRECTORY/log-Release-Android"
	cd $DIR

	android/rebuild $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-Release-Android"

	ANDROID_ABI_TARGETS=""

	while read line
	do
		if [[ $line == Android* ]]; then
			ANDROID_ABI_TARGETS=$(echo $line | sed s/Android//)
		fi
	done <"$PROJECT_DIRECTORY/development/build-system-targets"

	ANDROID_ABI_RESULTS=""

	for d in $PROJECT_DIRECTORY/development/android/libs/* ; do
		PREFIX=$PROJECT_DIRECTORY/development/android/libs/
		SUFFIX=/
		LIB_NAME=${d#$PREFIX}
		LIB_NAME=${LIB_NAME%$SUFFIX}
		ANDROID_ABI_RESULTS="$ANDROID_ABI_RESULTS $LIB_NAME"

		if ! [ -e "$d/libRakNet.so" ]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libRakNet.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2main.so" ]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2main.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2.so" ]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2_image.so" ]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2_image.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libSDL2_mixer.so" ]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libSDL2_mixer.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi

		if ! [ -e "$d/libmain.so" ]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing library '$d/libmain.so'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi
	done

	IFS=' ' read -a ARRAY <<< "$ANDROID_ABI_TARGETS"
	for i in "${ARRAY[@]}" ; do
		if ! [[ $ANDROID_ABI_RESULTS == *"$i"* ]]; then
			echo "rebuild-android failed for $PROJECT_DIRECTORY: missing ABI '$i'" | tee -a "$PROJECT_DIRECTORY/log-Release-Android"
			exit
		fi
	done

	android/ant $PROJECT_DIRECTORY release rebuild >> "$PROJECT_DIRECTORY/log-Release-Android"
else
	echo "rebuild-android - rebuild the android target for the passed project"
	echo "Usage: rebuild-android PROJECT-DIRECTORY"
fi
