#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1
TARGET=$2

if [ -n "$PROJECT_DIRECTORY" ] && [ -n "$TARGET" ]; then
	./clean-project $PROJECT_DIRECTORY

	./build-target $PROJECT_DIRECTORY $TARGET
else
	echo "rebuild-target - rebuild the passed target for the passed project"
	echo "Usage: rebuild-target PROJECT-DIRECTORY TARGET"
fi
