#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./rebuild-target $PROJECT_DIRECTORY Release-Linux-x86_64

	./rebuild-target $PROJECT_DIRECTORY Release-Linux-x86

	./rebuild-target $PROJECT_DIRECTORY Cross-Compile-Windows-x86_64

	./rebuild-target $PROJECT_DIRECTORY Release-Windows-x86

	./rebuild-target $PROJECT_DIRECTORY Release-macOS-x86_64

	./rebuild-android $PROJECT_DIRECTORY
else
	echo "rebuild-all - rebuild all targets for the passed project"
	echo "Usage: rebuild-all PROJECT-DIRECTORY"
fi
