#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1
TARGET=$2

if [ -n "$PROJECT_DIRECTORY" ] && [ -n "$TARGET" ]; then
	../../Build-Date-Linux-x86_64 $PROJECT_DIRECTORY >> "$PROJECT_DIRECTORY/log-$TARGET"

	codeblocks --rebuild --target="$TARGET" "$PROJECT_DIRECTORY/project.cbp" >> "$PROJECT_DIRECTORY/log-$TARGET"
else
	echo "rebuild-target - rebuild the passed target for the passed project"
	echo "Usage: rebuild-target PROJECT-DIRECTORY TARGET"
fi
