set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_C_COMPILER o64-clang)
set(CMAKE_CXX_COMPILER o64-clang++)
set(CMAKE_EXE_LINKER_FLAGS_INIT -DCMAKE_CXX_FLAGS='-fuse-ld=o64-ld')
set(CMAKE_MODULE_LINKER_FLAGS_INIT -DCMAKE_CXX_FLAGS='-fuse-ld=o64-ld')
set(CMAKE_SHARED_LINKER_FLAGS_INIT -DCMAKE_CXX_FLAGS='-fuse-ld=o64-ld')
set(CMAKE_FIND_ROOT_PATH /home/tails/build-server/osx-x86_64/osxcross/target)
