#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	NDK_PROJECT_PATH="$PROJECT_DIRECTORY/development/android"

	/home/tails/build-server/android/android-ndk/ndk-build
else
	echo "build - run ndk-build on the passed project"
	echo "Usage: build PROJECT_DIRECTORY"
fi
