#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1
TARGET=$2
ACTION=$3

if [ -n "$PROJECT_DIRECTORY" ] && [ -n "$TARGET" ]; then
	if [ "$TARGET" != "release" ] && [ "$TARGET" != "debug" ]; then
		echo "TARGET must be either 'release' or 'debug'"

		exit 64
	fi

	if [ -n "$ACTION" ]; then
		if [ "$ACTION" != "clean" ] && [ "$ACTION" != "rebuild" ] && [ "$ACTION" != "install" ]; then
			echo "ACTION must be either '', 'clean', 'rebuild', or 'install'"

			exit 65
		fi
	fi

	JAVA_HOME=/usr/lib/jvm/default-java

	cd "$PROJECT_DIRECTORY/development/android"

	if [ -z "$ACTION" ]; then
		ant $TARGET
	elif [ "$ACTION" == "rebuild" ]; then
		ant $TARGET clean
		ant $TARGET build
	else
		ant $TARGET $ACTION
	fi
else
	echo "ant - run ant on the passed project"
	echo "Usage: ant PROJECT-DIRECTORY TARGET ACTION"
	echo "TARGET must be either 'release' or 'debug'"
	echo "ACTION must be either '', 'clean', 'rebuild', or 'install'"
fi
