#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1

if [ -n "$PROJECT_DIRECTORY" ]; then
	./clean $PROJECT_DIRECTORY

	./build $PROJECT_DIRECTORY
else
	echo "rebuild - run ndk-build clean and ndk-build on the passed project"
	echo "Usage: rebuild PROJECT-DIRECTORY"
fi
