#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PROJECT_DIRECTORY=$1
KEY_STORE_LOCATION=$2
KEY_PASSWORDS_LOCATION=$3
KEY_ALIAS=$4

DIRECTORY_LIST=""
DIRECTORY_PREFIX=""
check_directories () {
	local directory=$1

	echo "Checking directory $directory"

	for d in $directory/*/ ; do
		if [ -d "$d" ]; then
			prefix=$directory/
			suffix=/
			dir_name=${d#$prefix}
			dir_name=${dir_name%$suffix}

			final_name="$directory/$dir_name"
			final_name=${final_name#$DIRECTORY_PREFIX}

			DIRECTORY_LIST="$DIRECTORY_LIST$final_name\n"

			check_directories "$directory/$dir_name"
		fi
	done
}

create_directory_list () {
	local directory=$1

	DIRECTORY_LIST=""
	DIRECTORY_PREFIX="$directory/"
	check_directories "$directory"

	echo -e "$DIRECTORY_LIST" >> "$directory/directory_list"
}

create_asset_list () {
	local directory=$1

	local assets=""

	for file in $directory/* ; do
		if [ -f "$file" ]; then
			prefix=$directory/
			file_name=${file#$prefix}

			assets="$assets$file_name\n"
		fi
	done

	echo -e "$assets" >> "$directory/asset_list"
}

create_asset_lists () {
	local directory=$1

	create_asset_list "$directory"

	for d in $directory/*/ ; do
		if [ -d "$d" ]; then
			prefix=$directory/
			suffix=/
			dir_name=${d#$prefix}
			dir_name=${dir_name%$suffix}

			create_asset_lists "$directory/$dir_name"
		fi
	done
}

if [ -n "$PROJECT_DIRECTORY" ] && [ -n "$KEY_PASSWORDS_LOCATION" ]; then
	ANDROID_DIRECTORY="$PROJECT_DIRECTORY/development/android"
	ENGINE_ANDROID_DIRECTORY="/home/tails/build-server/cheese-engine/tools/build-system/android"

	KEY_STORE_PASSWORD=$(sed -n '1{p;q;}' $KEY_PASSWORDS_LOCATION)
	ALIAS_PASSWORD=$(sed -n '2{p;q;}' $KEY_PASSWORDS_LOCATION)

	echo "Populating assets/ directory"

	rm -rf "$ANDROID_DIRECTORY/app/src/main/assets/"
	mkdir -p "$ANDROID_DIRECTORY/app/src/main/assets"
	cp "$PROJECT_DIRECTORY/save_location.cfg" "$ANDROID_DIRECTORY/app/src/main/assets/save_location.cfg"

	# Android always needs the save location to be set to home, so we will make sure it is set to that here
	sed -i -e 's/local/home/g' "$ANDROID_DIRECTORY/app/src/main/assets/save_location.cfg"

	cp -r "$PROJECT_DIRECTORY/data" "$ANDROID_DIRECTORY/app/src/main/assets"
	cp -r "$PROJECT_DIRECTORY/docs" "$ANDROID_DIRECTORY/app/src/main/assets"

	echo "Creating directory list"

	create_directory_list "$ANDROID_DIRECTORY/app/src/main/assets"

	echo "Creating asset lists"

	create_asset_lists "$ANDROID_DIRECTORY/app/src/main/assets/data"
	create_asset_lists "$ANDROID_DIRECTORY/app/src/main/assets/docs"

	echo "Copying prebuilt libraries"

	LIBRARY_LOCATION="/home/tails/build-server"
	declare -a abis=("arm64-v8a" "x86_64")
	for i in "${abis[@]}" ; do
		abi="$i"

		rm -rf "$ANDROID_DIRECTORY/app/jni/$abi/"
		mkdir -p "$ANDROID_DIRECTORY/app/jni/$abi"

		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libcpufeatures.a" "$ANDROID_DIRECTORY/app/jni/$abi/libcpufeatures.a"
		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libSDL2main.a" "$ANDROID_DIRECTORY/app/jni/$abi/libSDL2main.a"
		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libSDL2.a" "$ANDROID_DIRECTORY/app/jni/$abi/libSDL2.a"
		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libSDL2_image.a" "$ANDROID_DIRECTORY/app/jni/$abi/libSDL2_image.a"
		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libSDL2_mixer.a" "$ANDROID_DIRECTORY/app/jni/$abi/libSDL2_mixer.a"
		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libRakNet.a" "$ANDROID_DIRECTORY/app/jni/$abi/libRakNet.a"
		cp "$LIBRARY_LOCATION/cheese-engine/development/android/obj/local/$abi/libCheese-Engine.a" "$ANDROID_DIRECTORY/app/jni/$abi/libCheese-Engine.a"
	done

	echo "Creating symlinks to development libraries"

	rm -f "$ANDROID_DIRECTORY/app/jni/include/SDL2"
	rm -f "$ANDROID_DIRECTORY/app/jni/include/SDL2_image"
	rm -f "$ANDROID_DIRECTORY/app/jni/include/SDL2_mixer"
	rm -f "$ANDROID_DIRECTORY/app/jni/include/RakNet"
	rm -f "$ANDROID_DIRECTORY/app/jni/include/boost"
	rm -f "$ANDROID_DIRECTORY/app/jni/include/cheese-engine"

	rm -rf "$ANDROID_DIRECTORY/app/jni/include/"
	mkdir -p "$ANDROID_DIRECTORY/app/jni/include"

	ln -s "/home/tails/build-server/android/SDL2" "$ANDROID_DIRECTORY/app/jni/include/SDL2"
	ln -s "/home/tails/build-server/android/SDL2_image" "$ANDROID_DIRECTORY/app/jni/include/SDL2_image"
	ln -s "/home/tails/build-server/android/SDL2_mixer" "$ANDROID_DIRECTORY/app/jni/include/SDL2_mixer"
	ln -s "/home/tails/build-server/android/raknet/raknet" "$ANDROID_DIRECTORY/app/jni/include/RakNet"
	ln -s "/home/tails/build-server/linux-x86_64/boost" "$ANDROID_DIRECTORY/app/jni/include/boost"
	ln -s "/home/tails/build-server/cheese-engine" "$ANDROID_DIRECTORY/app/jni/include/cheese-engine"

	echo "Copying engine files"

	cp "$ENGINE_ANDROID_DIRECTORY/build.gradle" "$ANDROID_DIRECTORY/build.gradle"
	cp "$ENGINE_ANDROID_DIRECTORY/gradle.properties" "$ANDROID_DIRECTORY/gradle.properties"
	cp "$ENGINE_ANDROID_DIRECTORY/gradlew" "$ANDROID_DIRECTORY/gradlew"
	cp "$ENGINE_ANDROID_DIRECTORY/gradlew.bat" "$ANDROID_DIRECTORY/gradlew.bat"
	cp "$ENGINE_ANDROID_DIRECTORY/local.properties" "$ANDROID_DIRECTORY/local.properties"
	cp "$ENGINE_ANDROID_DIRECTORY/repositories.gradle" "$ANDROID_DIRECTORY/repositories.gradle"
	cp "$ENGINE_ANDROID_DIRECTORY/settings.gradle" "$ANDROID_DIRECTORY/settings.gradle"
	cp -r "$ENGINE_ANDROID_DIRECTORY/gradle" "$ANDROID_DIRECTORY"
	cp "$ENGINE_ANDROID_DIRECTORY/app/build.gradle" "$ANDROID_DIRECTORY/app/build.gradle"
	cp "$ENGINE_ANDROID_DIRECTORY/app/proguard-rules.pro" "$ANDROID_DIRECTORY/app/proguard-rules.pro"
	cp -r "$ENGINE_ANDROID_DIRECTORY/app/src/main/java/org/libsdl" "$ANDROID_DIRECTORY/app/src/main/java/org"
	cp -r "$ENGINE_ANDROID_DIRECTORY/app/jni" "$ANDROID_DIRECTORY/app"

	VERSION_CODE_FILE="$ANDROID_DIRECTORY/versionCode"
	VERSION_CODE=$(sed -e "/^[0-9]+$/p" "$VERSION_CODE_FILE" | sed -e "s/[^0-9]//g")
	VERSION_FILE="$PROJECT_DIRECTORY/src/version.cpp"
	VERSION_NAME=""
	if [ -n "$VERSION_FILE" ]; then
		OLD_MAJOR=$(sed -ne "/^.*\/\/ MAJOR$/p" "$VERSION_FILE" | sed -e "s/[^0-9]//g")
		OLD_MINOR=$(sed -ne "/^.*\/\/ MINOR$/p" "$VERSION_FILE" | sed -e "s/[^0-9]//g")
		OLD_PATCH=$(sed -ne "/^.*\/\/ PATCH$/p" "$VERSION_FILE" | sed -e "s/[^0-9]//g")
		VERSION_NAME="$OLD_MAJOR.$OLD_MINOR.$OLD_PATCH"
	fi
	sed -i -e "s/VERSION_CODE/$VERSION_CODE/g" "$ANDROID_DIRECTORY/build.gradle"
	sed -i -e "s/VERSION_NAME/$VERSION_NAME/g" "$ANDROID_DIRECTORY/build.gradle"

	APP_NAME_FILE="$ANDROID_DIRECTORY/appName"
	APP_NAME=$(sed -e "/^[A-Za-z]+$/p" "$APP_NAME_FILE")
	sed -i -e "s/APP_NAME/$APP_NAME/g" "$ANDROID_DIRECTORY/app/build.gradle"
	sed -i -e "s/APP_NAME/$APP_NAME/g" "$ANDROID_DIRECTORY/app/src/main/java/org/libsdl/app/SDLActivity.java"

	sed -i -e "s/KEY_ALIAS/$KEY_ALIAS/g" "$ANDROID_DIRECTORY/app/build.gradle"
	sed -i -e "s/KEY_PASSWORD/$ALIAS_PASSWORD/g" "$ANDROID_DIRECTORY/app/build.gradle"
	sed -i -e "s/STORE_FILE/$(echo $KEY_STORE_LOCATION | sed -e 's/\//\\\//g; s/\./\\\./g')/g" "$ANDROID_DIRECTORY/app/build.gradle"
	sed -i -e "s/STORE_PASSWORD/$KEY_STORE_PASSWORD/g" "$ANDROID_DIRECTORY/app/build.gradle"
else
	echo "android-prep - prepare the android/ directory of a Cheese Engine project for building"
	echo "Usage: android-prep PROJECT-DIRECTORY KEY-STORE-LOCATION KEY-PASSWORDS-LOCATION KEY-ALIAS"
fi
