#!/bin/bash

CI_JOB_NAME=$1
CI_BUILD_NUMBER=$2
CI_BUILD_URL=$3

updateFeed () {
	local prefix=$1
	local ciJobName=$2
	local ciBuildNumber=$3
	local ciBuildUrl=$4

	title="$prefix$ciJobName $ciBuildNumber"
    content="$title (<a href=\"$ciBuildUrl\">$ciBuildUrl</a>)"

    /home/tails/build-server/cheese-engine/tools/postToFeed "$(pwd)" "jenkins" "Wells Family Jenkins" "Tails" \
    "tails.at.mobius@gmail.com" "https://wells-family.xyz/" "https://wells-family.xyz/favicon.png" "$title" "$content" \
    "$ciBuildUrl"
}

if [ -n "$CI_JOB_NAME" ] && [ -n "$CI_BUILD_NUMBER" ] && [ -n "$CI_BUILD_URL" ]; then
	updateFeed "Build started - " "$CI_JOB_NAME" "$CI_BUILD_NUMBER" "$CI_BUILD_URL"

	if /home/tails/build-server/cheese-engine/tools/build-system/build "$(pwd)" "true" ; then
		updateFeed "Build completed successfully - " "$CI_JOB_NAME" "$CI_BUILD_NUMBER" "$CI_BUILD_URL"
		exit 0
	else
		updateFeed "Build failed - " "$CI_JOB_NAME" "$CI_BUILD_NUMBER" "$CI_BUILD_URL"
		exit 1
	fi
else
	echo "ciCd - run the CI / CD steps (call from Jenkins)"
	echo "Usage: ciCd CI_JOB_NAME CI_BUILD_NUMBER CI_BUILD_URL"
fi
